export const rankings = [
  {
    Economy: "New Zealand",
    Global_Rank: 1,
    Starting_a_Business: 1,
    Dealing_with_Construction_Permits: 6,
    Getting_Electricity: 45,
    Registering_Property: 1,
    Getting_Credit: 1,
    Protecting_Minority_Investors: 2,
    Paying_Taxes: 10,
    Trading_across_Borders: 60,
    Enforcing_Contracts: 21,
    Resolving_Insolvency: 31
  },
  {
    Economy: "Singapore",
    Global_Rank: 2,
    Starting_a_Business: 3,
    Dealing_with_Construction_Permits: 8,
    Getting_Electricity: 16,
    Registering_Property: 21,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 7,
    Paying_Taxes: 8,
    Trading_across_Borders: 45,
    Enforcing_Contracts: 1,
    Resolving_Insolvency: 27
  },
  {
    Economy: "Denmark",
    Global_Rank: 3,
    Starting_a_Business: 42,
    Dealing_with_Construction_Permits: 4,
    Getting_Electricity: 21,
    Registering_Property: 11,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 9,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 14,
    Resolving_Insolvency: 6
  },
  {
    Economy: "Hong Kong SAR, China",
    Global_Rank: 4,
    Starting_a_Business: 5,
    Dealing_with_Construction_Permits: 1,
    Getting_Electricity: 3,
    Registering_Property: 53,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 11,
    Paying_Taxes: 1,
    Trading_across_Borders: 27,
    Enforcing_Contracts: 30,
    Resolving_Insolvency: 44
  },
  {
    Economy: "Korea, Rep.",
    Global_Rank: 5,
    Starting_a_Business: 11,
    Dealing_with_Construction_Permits: 10,
    Getting_Electricity: 2,
    Registering_Property: 40,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 23,
    Paying_Taxes: 24,
    Trading_across_Borders: 33,
    Enforcing_Contracts: 2,
    Resolving_Insolvency: 11
  },
  {
    Economy: "Georgia",
    Global_Rank: 6,
    Starting_a_Business: 2,
    Dealing_with_Construction_Permits: 27,
    Getting_Electricity: 39,
    Registering_Property: 4,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 2,
    Paying_Taxes: 16,
    Trading_across_Borders: 43,
    Enforcing_Contracts: 8,
    Resolving_Insolvency: 60
  },
  {
    Economy: "Norway",
    Global_Rank: 7,
    Starting_a_Business: 22,
    Dealing_with_Construction_Permits: 22,
    Getting_Electricity: 19,
    Registering_Property: 13,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 30,
    Trading_across_Borders: 22,
    Enforcing_Contracts: 3,
    Resolving_Insolvency: 5
  },
  {
    Economy: "United States",
    Global_Rank: 8,
    Starting_a_Business: 53,
    Dealing_with_Construction_Permits: 26,
    Getting_Electricity: 54,
    Registering_Property: 38,
    Getting_Credit: 3,
    Protecting_Minority_Investors: 50,
    Paying_Taxes: 37,
    Trading_across_Borders: 36,
    Enforcing_Contracts: 16,
    Resolving_Insolvency: 3
  },
  {
    Economy: "United Kingdom",
    Global_Rank: 9,
    Starting_a_Business: 19,
    Dealing_with_Construction_Permits: 17,
    Getting_Electricity: 7,
    Registering_Property: 42,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 23,
    Trading_across_Borders: 30,
    Enforcing_Contracts: 32,
    Resolving_Insolvency: 14
  },
  {
    Economy: "Macedonia, FYR",
    Global_Rank: 10,
    Starting_a_Business: 47,
    Dealing_with_Construction_Permits: 13,
    Getting_Electricity: 57,
    Registering_Property: 46,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 7,
    Paying_Taxes: 31,
    Trading_across_Borders: 29,
    Enforcing_Contracts: 37,
    Resolving_Insolvency: 30
  },
  {
    Economy: "United Arab Emirates",
    Global_Rank: 11,
    Starting_a_Business: 25,
    Dealing_with_Construction_Permits: 5,
    Getting_Electricity: 1,
    Registering_Property: 7,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 2,
    Trading_across_Borders: 98,
    Enforcing_Contracts: 9,
    Resolving_Insolvency: 75
  },
  {
    Economy: "Sweden",
    Global_Rank: 12,
    Starting_a_Business: 18,
    Dealing_with_Construction_Permits: 25,
    Getting_Electricity: 9,
    Registering_Property: 10,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 33,
    Paying_Taxes: 27,
    Trading_across_Borders: 18,
    Enforcing_Contracts: 38,
    Resolving_Insolvency: 17
  },
  {
    Economy: "Taiwan, China",
    Global_Rank: 13,
    Starting_a_Business: 20,
    Dealing_with_Construction_Permits: 2,
    Getting_Electricity: 8,
    Registering_Property: 19,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 29,
    Trading_across_Borders: 58,
    Enforcing_Contracts: 11,
    Resolving_Insolvency: 23
  },
  {
    Economy: "Lithuania",
    Global_Rank: 14,
    Starting_a_Business: 31,
    Dealing_with_Construction_Permits: 7,
    Getting_Electricity: 26,
    Registering_Property: 3,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 18,
    Trading_across_Borders: 19,
    Enforcing_Contracts: 7,
    Resolving_Insolvency: 85
  },
  {
    Economy: "Malaysia",
    Global_Rank: 15,
    Starting_a_Business: 122,
    Dealing_with_Construction_Permits: 3,
    Getting_Electricity: 4,
    Registering_Property: 29,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 2,
    Paying_Taxes: 72,
    Trading_across_Borders: 48,
    Enforcing_Contracts: 33,
    Resolving_Insolvency: 41
  },
  {
    Economy: "Estonia",
    Global_Rank: 16,
    Starting_a_Business: 15,
    Dealing_with_Construction_Permits: 14,
    Getting_Electricity: 46,
    Registering_Property: 6,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 14,
    Trading_across_Borders: 17,
    Enforcing_Contracts: 13,
    Resolving_Insolvency: 47
  },
  {
    Economy: "Finland",
    Global_Rank: 17,
    Starting_a_Business: 43,
    Dealing_with_Construction_Permits: 34,
    Getting_Electricity: 25,
    Registering_Property: 28,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 11,
    Trading_across_Borders: 34,
    Enforcing_Contracts: 46,
    Resolving_Insolvency: 2
  },
  {
    Economy: "Australia",
    Global_Rank: 18,
    Starting_a_Business: 7,
    Dealing_with_Construction_Permits: 9,
    Getting_Electricity: 52,
    Registering_Property: 50,
    Getting_Credit: 8,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 26,
    Trading_across_Borders: 103,
    Enforcing_Contracts: 5,
    Resolving_Insolvency: 20
  },
  {
    Economy: "Latvia",
    Global_Rank: 19,
    Starting_a_Business: 24,
    Dealing_with_Construction_Permits: 56,
    Getting_Electricity: 53,
    Registering_Property: 25,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 13,
    Trading_across_Borders: 26,
    Enforcing_Contracts: 20,
    Resolving_Insolvency: 54
  },
  {
    Economy: "Mauritius",
    Global_Rank: 20,
    Starting_a_Business: 21,
    Dealing_with_Construction_Permits: 15,
    Getting_Electricity: 34,
    Registering_Property: 35,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 6,
    Trading_across_Borders: 69,
    Enforcing_Contracts: 27,
    Resolving_Insolvency: 35
  },
  {
    Economy: "Iceland",
    Global_Rank: 21,
    Starting_a_Business: 59,
    Dealing_with_Construction_Permits: 71,
    Getting_Electricity: 13,
    Registering_Property: 15,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 30,
    Paying_Taxes: 33,
    Trading_across_Borders: 53,
    Enforcing_Contracts: 31,
    Resolving_Insolvency: 12
  },
  {
    Economy: "Canada",
    Global_Rank: 22,
    Starting_a_Business: 3,
    Dealing_with_Construction_Permits: 63,
    Getting_Electricity: 121,
    Registering_Property: 34,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 11,
    Paying_Taxes: 19,
    Trading_across_Borders: 50,
    Enforcing_Contracts: 96,
    Resolving_Insolvency: 13
  },
  {
    Economy: "Ireland",
    Global_Rank: 23,
    Starting_a_Business: 10,
    Dealing_with_Construction_Permits: 28,
    Getting_Electricity: 43,
    Registering_Property: 64,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 4,
    Trading_across_Borders: 52,
    Enforcing_Contracts: 102,
    Resolving_Insolvency: 18
  },
  {
    Economy: "Germany",
    Global_Rank: 24,
    Starting_a_Business: 114,
    Dealing_with_Construction_Permits: 24,
    Getting_Electricity: 5,
    Registering_Property: 78,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 43,
    Trading_across_Borders: 40,
    Enforcing_Contracts: 26,
    Resolving_Insolvency: 4
  },
  {
    Economy: "Azerbaijan",
    Global_Rank: 25,
    Starting_a_Business: 9,
    Dealing_with_Construction_Permits: 61,
    Getting_Electricity: 74,
    Registering_Property: 17,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 2,
    Paying_Taxes: 28,
    Trading_across_Borders: 84,
    Enforcing_Contracts: 40,
    Resolving_Insolvency: 45
  },
  {
    Economy: "Austria",
    Global_Rank: 26,
    Starting_a_Business: 118,
    Dealing_with_Construction_Permits: 42,
    Getting_Electricity: 28,
    Registering_Property: 32,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 33,
    Paying_Taxes: 40,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 10,
    Resolving_Insolvency: 21
  },
  {
    Economy: "Thailand",
    Global_Rank: 27,
    Starting_a_Business: 39,
    Dealing_with_Construction_Permits: 67,
    Getting_Electricity: 6,
    Registering_Property: 66,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 59,
    Trading_across_Borders: 59,
    Enforcing_Contracts: 35,
    Resolving_Insolvency: 24
  },
  {
    Economy: "Kazakhstan",
    Global_Rank: 28,
    Starting_a_Business: 36,
    Dealing_with_Construction_Permits: 35,
    Getting_Electricity: 76,
    Registering_Property: 18,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 1,
    Paying_Taxes: 56,
    Trading_across_Borders: 102,
    Enforcing_Contracts: 4,
    Resolving_Insolvency: 37
  },
  {
    Economy: "Rwanda",
    Global_Rank: 29,
    Starting_a_Business: 51,
    Dealing_with_Construction_Permits: 106,
    Getting_Electricity: 68,
    Registering_Property: 2,
    Getting_Credit: 3,
    Protecting_Minority_Investors: 14,
    Paying_Taxes: 35,
    Trading_across_Borders: 88,
    Enforcing_Contracts: 78,
    Resolving_Insolvency: 58
  },
  {
    Economy: "Spain",
    Global_Rank: 30,
    Starting_a_Business: 86,
    Dealing_with_Construction_Permits: 78,
    Getting_Electricity: 48,
    Registering_Property: 58,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 30,
    Paying_Taxes: 34,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 23,
    Resolving_Insolvency: 19
  },
  {
    Economy: "Russian Federation",
    Global_Rank: 31,
    Starting_a_Business: 32,
    Dealing_with_Construction_Permits: 48,
    Getting_Electricity: 12,
    Registering_Property: 12,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 53,
    Trading_across_Borders: 99,
    Enforcing_Contracts: 18,
    Resolving_Insolvency: 55
  },
  {
    Economy: "France",
    Global_Rank: 32,
    Starting_a_Business: 30,
    Dealing_with_Construction_Permits: 19,
    Getting_Electricity: 14,
    Registering_Property: 96,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 55,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 12,
    Resolving_Insolvency: 28
  },
  {
    Economy: "Poland",
    Global_Rank: 33,
    Starting_a_Business: 121,
    Dealing_with_Construction_Permits: 40,
    Getting_Electricity: 58,
    Registering_Property: 41,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 69,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 53,
    Resolving_Insolvency: 25
  },
  {
    Economy: "Portugal",
    Global_Rank: 34,
    Starting_a_Business: 57,
    Dealing_with_Construction_Permits: 60,
    Getting_Electricity: 32,
    Registering_Property: 36,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 39,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 35,
    Resolving_Insolvency: 16
  },
  {
    Economy: "Czech Republic",
    Global_Rank: 35,
    Starting_a_Business: 115,
    Dealing_with_Construction_Permits: 156,
    Getting_Electricity: 10,
    Registering_Property: 33,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 45,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 99,
    Resolving_Insolvency: 15
  },
  {
    Economy: "Netherlands",
    Global_Rank: 36,
    Starting_a_Business: 22,
    Dealing_with_Construction_Permits: 84,
    Getting_Electricity: 56,
    Registering_Property: 31,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 21,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 74,
    Resolving_Insolvency: 7
  },
  {
    Economy: "Belarus",
    Global_Rank: 37,
    Starting_a_Business: 29,
    Dealing_with_Construction_Permits: 46,
    Getting_Electricity: 20,
    Registering_Property: 5,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 99,
    Trading_across_Borders: 25,
    Enforcing_Contracts: 29,
    Resolving_Insolvency: 72
  },
  {
    Economy: "Switzerland",
    Global_Rank: 38,
    Starting_a_Business: 77,
    Dealing_with_Construction_Permits: 69,
    Getting_Electricity: 11,
    Registering_Property: 16,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 20,
    Trading_across_Borders: 39,
    Enforcing_Contracts: 55,
    Resolving_Insolvency: 46
  },
  {
    Economy: "Japan",
    Global_Rank: 39,
    Starting_a_Business: 93,
    Dealing_with_Construction_Permits: 44,
    Getting_Electricity: 22,
    Registering_Property: 48,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 97,
    Trading_across_Borders: 56,
    Enforcing_Contracts: 52,
    Resolving_Insolvency: 1
  },
  {
    Economy: "Slovenia",
    Global_Rank: 40,
    Starting_a_Business: 38,
    Dealing_with_Construction_Permits: 120,
    Getting_Electricity: 23,
    Registering_Property: 56,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 30,
    Paying_Taxes: 41,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 110,
    Resolving_Insolvency: 9
  },
  {
    Economy: "Armenia",
    Global_Rank: 41,
    Starting_a_Business: 8,
    Dealing_with_Construction_Permits: 98,
    Getting_Electricity: 17,
    Registering_Property: 14,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 82,
    Trading_across_Borders: 46,
    Enforcing_Contracts: 24,
    Resolving_Insolvency: 95
  },
  {
    Economy: "Slovak Republic",
    Global_Rank: 42,
    Starting_a_Business: 127,
    Dealing_with_Construction_Permits: 143,
    Getting_Electricity: 47,
    Registering_Property: 9,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 95,
    Paying_Taxes: 48,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 47,
    Resolving_Insolvency: 42
  },
  {
    Economy: "Turkey",
    Global_Rank: 43,
    Starting_a_Business: 78,
    Dealing_with_Construction_Permits: 59,
    Getting_Electricity: 60,
    Registering_Property: 39,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 26,
    Paying_Taxes: 80,
    Trading_across_Borders: 42,
    Enforcing_Contracts: 19,
    Resolving_Insolvency: 109
  },
  {
    Economy: "Kosovo",
    Global_Rank: 44,
    Starting_a_Business: 13,
    Dealing_with_Construction_Permits: 100,
    Getting_Electricity: 113,
    Registering_Property: 37,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 95,
    Paying_Taxes: 44,
    Trading_across_Borders: 51,
    Enforcing_Contracts: 50,
    Resolving_Insolvency: 50
  },
  {
    Economy: "Belgium",
    Global_Rank: 45,
    Starting_a_Business: 33,
    Dealing_with_Construction_Permits: 38,
    Getting_Electricity: 112,
    Registering_Property: 143,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 60,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 54,
    Resolving_Insolvency: 8
  },
  {
    Economy: "China",
    Global_Rank: 46,
    Starting_a_Business: 28,
    Dealing_with_Construction_Permits: 121,
    Getting_Electricity: 14,
    Registering_Property: 27,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 114,
    Trading_across_Borders: 65,
    Enforcing_Contracts: 6,
    Resolving_Insolvency: 61
  },
  {
    Economy: "Moldova",
    Global_Rank: 47,
    Starting_a_Business: 14,
    Dealing_with_Construction_Permits: 172,
    Getting_Electricity: 81,
    Registering_Property: 22,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 33,
    Paying_Taxes: 35,
    Trading_across_Borders: 35,
    Enforcing_Contracts: 69,
    Resolving_Insolvency: 68
  },
  {
    Economy: "Serbia",
    Global_Rank: 48,
    Starting_a_Business: 40,
    Dealing_with_Construction_Permits: 11,
    Getting_Electricity: 104,
    Registering_Property: 55,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 79,
    Trading_across_Borders: 23,
    Enforcing_Contracts: 65,
    Resolving_Insolvency: 49
  },
  {
    Economy: "Israel",
    Global_Rank: 49,
    Starting_a_Business: 45,
    Dealing_with_Construction_Permits: 41,
    Getting_Electricity: 78,
    Registering_Property: 89,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 23,
    Paying_Taxes: 90,
    Trading_across_Borders: 64,
    Enforcing_Contracts: 90,
    Resolving_Insolvency: 29
  },
  {
    Economy: "Montenegro",
    Global_Rank: 50,
    Starting_a_Business: 90,
    Dealing_with_Construction_Permits: 75,
    Getting_Electricity: 134,
    Registering_Property: 76,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 68,
    Trading_across_Borders: 47,
    Enforcing_Contracts: 44,
    Resolving_Insolvency: 43
  },
  {
    Economy: "Italy",
    Global_Rank: 51,
    Starting_a_Business: 67,
    Dealing_with_Construction_Permits: 104,
    Getting_Electricity: 37,
    Registering_Property: 23,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 118,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 111,
    Resolving_Insolvency: 22
  },
  {
    Economy: "Romania",
    Global_Rank: 52,
    Starting_a_Business: 111,
    Dealing_with_Construction_Permits: 146,
    Getting_Electricity: 154,
    Registering_Property: 44,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 49,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 17,
    Resolving_Insolvency: 52
  },
  {
    Economy: "Hungary",
    Global_Rank: 53,
    Starting_a_Business: 82,
    Dealing_with_Construction_Permits: 110,
    Getting_Electricity: 122,
    Registering_Property: 30,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 86,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 22,
    Resolving_Insolvency: 65
  },
  {
    Economy: "Mexico",
    Global_Rank: 54,
    Starting_a_Business: 94,
    Dealing_with_Construction_Permits: 93,
    Getting_Electricity: 99,
    Registering_Property: 103,
    Getting_Credit: 8,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 116,
    Trading_across_Borders: 66,
    Enforcing_Contracts: 43,
    Resolving_Insolvency: 32
  },
  {
    Economy: "Brunei Darussalam",
    Global_Rank: 55,
    Starting_a_Business: 16,
    Dealing_with_Construction_Permits: 55,
    Getting_Electricity: 31,
    Registering_Property: 142,
    Getting_Credit: 1,
    Protecting_Minority_Investors: 48,
    Paying_Taxes: 84,
    Trading_across_Borders: 149,
    Enforcing_Contracts: 67,
    Resolving_Insolvency: 64
  },
  {
    Economy: "Chile",
    Global_Rank: 56,
    Starting_a_Business: 72,
    Dealing_with_Construction_Permits: 33,
    Getting_Electricity: 36,
    Registering_Property: 61,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 76,
    Trading_across_Borders: 71,
    Enforcing_Contracts: 49,
    Resolving_Insolvency: 51
  },
  {
    Economy: "Cyprus",
    Global_Rank: 57,
    Starting_a_Business: 52,
    Dealing_with_Construction_Permits: 126,
    Getting_Electricity: 70,
    Registering_Property: 94,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 47,
    Trading_across_Borders: 49,
    Enforcing_Contracts: 138,
    Resolving_Insolvency: 26
  },
  {
    Economy: "Croatia",
    Global_Rank: 58,
    Starting_a_Business: 123,
    Dealing_with_Construction_Permits: 159,
    Getting_Electricity: 61,
    Registering_Property: 51,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 89,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 25,
    Resolving_Insolvency: 59
  },
  {
    Economy: "Bulgaria",
    Global_Rank: 59,
    Starting_a_Business: 99,
    Dealing_with_Construction_Permits: 37,
    Getting_Electricity: 147,
    Registering_Property: 67,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 33,
    Paying_Taxes: 92,
    Trading_across_Borders: 21,
    Enforcing_Contracts: 42,
    Resolving_Insolvency: 56
  },
  {
    Economy: "Morocco",
    Global_Rank: 60,
    Starting_a_Business: 34,
    Dealing_with_Construction_Permits: 18,
    Getting_Electricity: 59,
    Registering_Property: 68,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 25,
    Trading_across_Borders: 62,
    Enforcing_Contracts: 68,
    Resolving_Insolvency: 71
  },
  {
    Economy: "Kenya",
    Global_Rank: 61,
    Starting_a_Business: 126,
    Dealing_with_Construction_Permits: 128,
    Getting_Electricity: 75,
    Registering_Property: 122,
    Getting_Credit: 8,
    Protecting_Minority_Investors: 11,
    Paying_Taxes: 91,
    Trading_across_Borders: 112,
    Enforcing_Contracts: 88,
    Resolving_Insolvency: 57
  },
  {
    Economy: "Bahrain",
    Global_Rank: 62,
    Starting_a_Business: 66,
    Dealing_with_Construction_Permits: 57,
    Getting_Electricity: 82,
    Registering_Property: 26,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 5,
    Trading_across_Borders: 77,
    Enforcing_Contracts: 128,
    Resolving_Insolvency: 93
  },
  {
    Economy: "Albania",
    Global_Rank: 63,
    Starting_a_Business: 50,
    Dealing_with_Construction_Permits: 151,
    Getting_Electricity: 140,
    Registering_Property: 98,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 26,
    Paying_Taxes: 122,
    Trading_across_Borders: 24,
    Enforcing_Contracts: 98,
    Resolving_Insolvency: 39
  },
  {
    Economy: "Puerto Rico (U.S.)",
    Global_Rank: 64,
    Starting_a_Business: 53,
    Dealing_with_Construction_Permits: 141,
    Getting_Electricity: 88,
    Registering_Property: 159,
    Getting_Credit: 3,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 162,
    Trading_across_Borders: 67,
    Enforcing_Contracts: 63,
    Resolving_Insolvency: 10
  },
  {
    Economy: "Colombia",
    Global_Rank: 65,
    Starting_a_Business: 100,
    Dealing_with_Construction_Permits: 89,
    Getting_Electricity: 80,
    Registering_Property: 59,
    Getting_Credit: 3,
    Protecting_Minority_Investors: 15,
    Paying_Taxes: 146,
    Trading_across_Borders: 133,
    Enforcing_Contracts: 177,
    Resolving_Insolvency: 40
  },
  {
    Economy: "Luxembourg",
    Global_Rank: 66,
    Starting_a_Business: 73,
    Dealing_with_Construction_Permits: 12,
    Getting_Electricity: 41,
    Registering_Property: 92,
    Getting_Credit: 175,
    Protecting_Minority_Investors: 122,
    Paying_Taxes: 22,
    Trading_across_Borders: 1,
    Enforcing_Contracts: 15,
    Resolving_Insolvency: 90
  },
  {
    Economy: "Costa Rica",
    Global_Rank: 67,
    Starting_a_Business: 142,
    Dealing_with_Construction_Permits: 74,
    Getting_Electricity: 38,
    Registering_Property: 47,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 122,
    Paying_Taxes: 57,
    Trading_across_Borders: 73,
    Enforcing_Contracts: 121,
    Resolving_Insolvency: 134
  },
  {
    Economy: "Peru",
    Global_Rank: 68,
    Starting_a_Business: 125,
    Dealing_with_Construction_Permits: 54,
    Getting_Electricity: 67,
    Registering_Property: 45,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 120,
    Trading_across_Borders: 110,
    Enforcing_Contracts: 70,
    Resolving_Insolvency: 88
  },
  {
    Economy: "Vietnam",
    Global_Rank: 69,
    Starting_a_Business: 104,
    Dealing_with_Construction_Permits: 21,
    Getting_Electricity: 27,
    Registering_Property: 60,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 131,
    Trading_across_Borders: 100,
    Enforcing_Contracts: 62,
    Resolving_Insolvency: 133
  },
  {
    Economy: "Kyrgyz Republic",
    Global_Rank: 70,
    Starting_a_Business: 35,
    Dealing_with_Construction_Permits: 29,
    Getting_Electricity: 164,
    Registering_Property: 8,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 150,
    Trading_across_Borders: 70,
    Enforcing_Contracts: 131,
    Resolving_Insolvency: 82
  },
  {
    Economy: "Ukraine",
    Global_Rank: 71,
    Starting_a_Business: 56,
    Dealing_with_Construction_Permits: 30,
    Getting_Electricity: 135,
    Registering_Property: 63,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 54,
    Trading_across_Borders: 78,
    Enforcing_Contracts: 57,
    Resolving_Insolvency: 145
  },
  {
    Economy: "Greece",
    Global_Rank: 72,
    Starting_a_Business: 44,
    Dealing_with_Construction_Permits: 39,
    Getting_Electricity: 79,
    Registering_Property: 153,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 65,
    Trading_across_Borders: 31,
    Enforcing_Contracts: 132,
    Resolving_Insolvency: 62
  },
  {
    Economy: "Indonesia",
    Global_Rank: 73,
    Starting_a_Business: 134,
    Dealing_with_Construction_Permits: 112,
    Getting_Electricity: 33,
    Registering_Property: 100,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 51,
    Paying_Taxes: 112,
    Trading_across_Borders: 116,
    Enforcing_Contracts: 146,
    Resolving_Insolvency: 36
  },
  {
    Economy: "Mongolia",
    Global_Rank: 74,
    Starting_a_Business: 87,
    Dealing_with_Construction_Permits: 23,
    Getting_Electricity: 148,
    Registering_Property: 49,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 33,
    Paying_Taxes: 61,
    Trading_across_Borders: 117,
    Enforcing_Contracts: 66,
    Resolving_Insolvency: 152
  },
  {
    Economy: "Jamaica",
    Global_Rank: 75,
    Starting_a_Business: 6,
    Dealing_with_Construction_Permits: 76,
    Getting_Electricity: 115,
    Registering_Property: 131,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 123,
    Trading_across_Borders: 134,
    Enforcing_Contracts: 127,
    Resolving_Insolvency: 33
  },
  {
    Economy: "Uzbekistan",
    Global_Rank: 76,
    Starting_a_Business: 12,
    Dealing_with_Construction_Permits: 134,
    Getting_Electricity: 35,
    Registering_Property: 71,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 64,
    Paying_Taxes: 64,
    Trading_across_Borders: 165,
    Enforcing_Contracts: 41,
    Resolving_Insolvency: 91
  },
  {
    Economy: "India",
    Global_Rank: 77,
    Starting_a_Business: 137,
    Dealing_with_Construction_Permits: 52,
    Getting_Electricity: 24,
    Registering_Property: 166,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 7,
    Paying_Taxes: 121,
    Trading_across_Borders: 80,
    Enforcing_Contracts: 163,
    Resolving_Insolvency: 108
  },
  {
    Economy: "Oman",
    Global_Rank: 78,
    Starting_a_Business: 37,
    Dealing_with_Construction_Permits: 66,
    Getting_Electricity: 66,
    Registering_Property: 52,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 12,
    Trading_across_Borders: 72,
    Enforcing_Contracts: 73,
    Resolving_Insolvency: 100
  },
  {
    Economy: "Panama",
    Global_Rank: 79,
    Starting_a_Business: 48,
    Dealing_with_Construction_Permits: 108,
    Getting_Electricity: 30,
    Registering_Property: 81,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 174,
    Trading_across_Borders: 57,
    Enforcing_Contracts: 147,
    Resolving_Insolvency: 113
  },
  {
    Economy: "Tunisia",
    Global_Rank: 80,
    Starting_a_Business: 63,
    Dealing_with_Construction_Permits: 77,
    Getting_Electricity: 51,
    Registering_Property: 87,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 133,
    Trading_across_Borders: 101,
    Enforcing_Contracts: 80,
    Resolving_Insolvency: 67
  },
  {
    Economy: "Bhutan",
    Global_Rank: 81,
    Starting_a_Business: 91,
    Dealing_with_Construction_Permits: 88,
    Getting_Electricity: 73,
    Registering_Property: 54,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 15,
    Trading_across_Borders: 28,
    Enforcing_Contracts: 28,
    Resolving_Insolvency: 168
  },
  {
    Economy: "South Africa",
    Global_Rank: 82,
    Starting_a_Business: 134,
    Dealing_with_Construction_Permits: 96,
    Getting_Electricity: 109,
    Registering_Property: 106,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 23,
    Paying_Taxes: 46,
    Trading_across_Borders: 143,
    Enforcing_Contracts: 115,
    Resolving_Insolvency: 66
  },
  {
    Economy: "Qatar",
    Global_Rank: 83,
    Starting_a_Business: 84,
    Dealing_with_Construction_Permits: 20,
    Getting_Electricity: 69,
    Registering_Property: 20,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 178,
    Paying_Taxes: 2,
    Trading_across_Borders: 97,
    Enforcing_Contracts: 122,
    Resolving_Insolvency: 120
  },
  {
    Economy: "Malta",
    Global_Rank: 84,
    Starting_a_Business: 103,
    Dealing_with_Construction_Permits: 45,
    Getting_Electricity: 77,
    Registering_Property: 151,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 71,
    Trading_across_Borders: 41,
    Enforcing_Contracts: 39,
    Resolving_Insolvency: 121
  },
  {
    Economy: "El Salvador",
    Global_Rank: 85,
    Starting_a_Business: 147,
    Dealing_with_Construction_Permits: 173,
    Getting_Electricity: 97,
    Registering_Property: 73,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 161,
    Paying_Taxes: 62,
    Trading_across_Borders: 44,
    Enforcing_Contracts: 109,
    Resolving_Insolvency: 89
  },
  {
    Economy: "Botswana",
    Global_Rank: 86,
    Starting_a_Business: 157,
    Dealing_with_Construction_Permits: 31,
    Getting_Electricity: 133,
    Registering_Property: 80,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 51,
    Trading_across_Borders: 55,
    Enforcing_Contracts: 134,
    Resolving_Insolvency: 81
  },
  {
    Economy: "Zambia",
    Global_Rank: 87,
    Starting_a_Business: 102,
    Dealing_with_Construction_Permits: 70,
    Getting_Electricity: 128,
    Registering_Property: 150,
    Getting_Credit: 3,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 17,
    Trading_across_Borders: 153,
    Enforcing_Contracts: 130,
    Resolving_Insolvency: 99
  },
  {
    Economy: "San Marino",
    Global_Rank: 88,
    Starting_a_Business: 113,
    Dealing_with_Construction_Permits: 72,
    Getting_Electricity: 18,
    Registering_Property: 101,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 177,
    Paying_Taxes: 42,
    Trading_across_Borders: 20,
    Enforcing_Contracts: 82,
    Resolving_Insolvency: 105
  },
  {
    Economy: "Bosnia and Herzegovina",
    Global_Rank: 89,
    Starting_a_Business: 183,
    Dealing_with_Construction_Permits: 167,
    Getting_Electricity: 130,
    Registering_Property: 99,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 139,
    Trading_across_Borders: 37,
    Enforcing_Contracts: 75,
    Resolving_Insolvency: 37
  },
  {
    Economy: "Samoa",
    Global_Rank: 90,
    Starting_a_Business: 41,
    Dealing_with_Construction_Permits: 90,
    Getting_Electricity: 65,
    Registering_Property: 65,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 74,
    Trading_across_Borders: 151,
    Enforcing_Contracts: 86,
    Resolving_Insolvency: 140
  },
  {
    Economy: "Tonga",
    Global_Rank: 91,
    Starting_a_Business: 58,
    Dealing_with_Construction_Permits: 16,
    Getting_Electricity: 90,
    Registering_Property: 163,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 100,
    Trading_across_Borders: 94,
    Enforcing_Contracts: 94,
    Resolving_Insolvency: 137
  },
  {
    Economy: "Saudi Arabia",
    Global_Rank: 92,
    Starting_a_Business: 141,
    Dealing_with_Construction_Permits: 36,
    Getting_Electricity: 64,
    Registering_Property: 24,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 7,
    Paying_Taxes: 78,
    Trading_across_Borders: 158,
    Enforcing_Contracts: 59,
    Resolving_Insolvency: 168
  },
  {
    Economy: "St. Lucia",
    Global_Rank: 93,
    Starting_a_Business: 70,
    Dealing_with_Construction_Permits: 32,
    Getting_Electricity: 49,
    Registering_Property: 104,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 73,
    Trading_across_Borders: 90,
    Enforcing_Contracts: 75,
    Resolving_Insolvency: 130
  },
  {
    Economy: "Vanuatu",
    Global_Rank: 94,
    Starting_a_Business: 132,
    Dealing_with_Construction_Permits: 147,
    Getting_Electricity: 107,
    Registering_Property: 79,
    Getting_Credit: 32,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 58,
    Trading_across_Borders: 147,
    Enforcing_Contracts: 136,
    Resolving_Insolvency: 98
  },
  {
    Economy: "Uruguay",
    Global_Rank: 95,
    Starting_a_Business: 65,
    Dealing_with_Construction_Permits: 155,
    Getting_Electricity: 55,
    Registering_Property: 115,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 101,
    Trading_across_Borders: 152,
    Enforcing_Contracts: 100,
    Resolving_Insolvency: 70
  },
  {
    Economy: "Seychelles",
    Global_Rank: 96,
    Starting_a_Business: 145,
    Dealing_with_Construction_Permits: 118,
    Getting_Electricity: 118,
    Registering_Property: 62,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 31,
    Trading_across_Borders: 95,
    Enforcing_Contracts: 129,
    Resolving_Insolvency: 73
  },
  {
    Economy: "Kuwait",
    Global_Rank: 97,
    Starting_a_Business: 133,
    Dealing_with_Construction_Permits: 131,
    Getting_Electricity: 95,
    Registering_Property: 69,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 7,
    Trading_across_Borders: 159,
    Enforcing_Contracts: 77,
    Resolving_Insolvency: 115
  },
  {
    Economy: "Guatemala",
    Global_Rank: 98,
    Starting_a_Business: 89,
    Dealing_with_Construction_Permits: 122,
    Getting_Electricity: 44,
    Registering_Property: 86,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 174,
    Paying_Taxes: 102,
    Trading_across_Borders: 83,
    Enforcing_Contracts: 176,
    Resolving_Insolvency: 156
  },
  {
    Economy: "Djibouti",
    Global_Rank: 99,
    Starting_a_Business: 96,
    Dealing_with_Construction_Permits: 101,
    Getting_Electricity: 119,
    Registering_Property: 110,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 2,
    Paying_Taxes: 108,
    Trading_across_Borders: 145,
    Enforcing_Contracts: 140,
    Resolving_Insolvency: 48
  },
  {
    Economy: "Sri Lanka",
    Global_Rank: 100,
    Starting_a_Business: 83,
    Dealing_with_Construction_Permits: 65,
    Getting_Electricity: 84,
    Registering_Property: 140,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 141,
    Trading_across_Borders: 93,
    Enforcing_Contracts: 164,
    Resolving_Insolvency: 92
  },
  {
    Economy: "Fiji",
    Global_Rank: 101,
    Starting_a_Business: 161,
    Dealing_with_Construction_Permits: 102,
    Getting_Electricity: 93,
    Registering_Property: 57,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 98,
    Trading_across_Borders: 79,
    Enforcing_Contracts: 97,
    Resolving_Insolvency: 96
  },
  {
    Economy: "Dominican Republic",
    Global_Rank: 102,
    Starting_a_Business: 117,
    Dealing_with_Construction_Permits: 80,
    Getting_Electricity: 116,
    Registering_Property: 77,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 83,
    Paying_Taxes: 148,
    Trading_across_Borders: 63,
    Enforcing_Contracts: 149,
    Resolving_Insolvency: 124
  },
  {
    Economy: "Dominica",
    Global_Rank: 103,
    Starting_a_Business: 69,
    Dealing_with_Construction_Permits: 82,
    Getting_Electricity: 50,
    Registering_Property: 168,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 75,
    Trading_across_Borders: 89,
    Enforcing_Contracts: 83,
    Resolving_Insolvency: 134
  },
  {
    Economy: "Jordan",
    Global_Rank: 104,
    Starting_a_Business: 106,
    Dealing_with_Construction_Permits: 139,
    Getting_Electricity: 62,
    Registering_Property: 72,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 95,
    Trading_across_Borders: 74,
    Enforcing_Contracts: 108,
    Resolving_Insolvency: 150
  },
  {
    Economy: "Trinidad and Tobago",
    Global_Rank: 105,
    Starting_a_Business: 76,
    Dealing_with_Construction_Permits: 125,
    Getting_Electricity: 41,
    Registering_Property: 158,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 166,
    Trading_across_Borders: 130,
    Enforcing_Contracts: 174,
    Resolving_Insolvency: 77
  },
  {
    Economy: "Lesotho",
    Global_Rank: 106,
    Starting_a_Business: 119,
    Dealing_with_Construction_Permits: 171,
    Getting_Electricity: 157,
    Registering_Property: 108,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 108,
    Trading_across_Borders: 38,
    Enforcing_Contracts: 95,
    Resolving_Insolvency: 126
  },
  {
    Economy: "Namibia",
    Global_Rank: 107,
    Starting_a_Business: 172,
    Dealing_with_Construction_Permits: 83,
    Getting_Electricity: 71,
    Registering_Property: 174,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 81,
    Trading_across_Borders: 136,
    Enforcing_Contracts: 58,
    Resolving_Insolvency: 125
  },
  {
    Economy: "Papua New Guinea",
    Global_Rank: 108,
    Starting_a_Business: 143,
    Dealing_with_Construction_Permits: 124,
    Getting_Electricity: 72,
    Registering_Property: 121,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 111,
    Trading_across_Borders: 140,
    Enforcing_Contracts: 173,
    Resolving_Insolvency: 142
  },
  {
    Economy: "Brazil",
    Global_Rank: 109,
    Starting_a_Business: 140,
    Dealing_with_Construction_Permits: 175,
    Getting_Electricity: 40,
    Registering_Property: 137,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 48,
    Paying_Taxes: 184,
    Trading_across_Borders: 106,
    Enforcing_Contracts: 48,
    Resolving_Insolvency: 77
  },
  {
    Economy: "Nepal",
    Global_Rank: 110,
    Starting_a_Business: 107,
    Dealing_with_Construction_Permits: 148,
    Getting_Electricity: 137,
    Registering_Property: 88,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 158,
    Trading_across_Borders: 82,
    Enforcing_Contracts: 154,
    Resolving_Insolvency: 83
  },
  {
    Economy: "Malawi",
    Global_Rank: 111,
    Starting_a_Business: 153,
    Dealing_with_Construction_Permits: 136,
    Getting_Electricity: 169,
    Registering_Property: 83,
    Getting_Credit: 8,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 134,
    Trading_across_Borders: 126,
    Enforcing_Contracts: 145,
    Resolving_Insolvency: 141
  },
  {
    Economy: "Antigua and Barbuda",
    Global_Rank: 112,
    Starting_a_Business: 131,
    Dealing_with_Construction_Permits: 97,
    Getting_Electricity: 63,
    Registering_Property: 120,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 144,
    Trading_across_Borders: 108,
    Enforcing_Contracts: 34,
    Resolving_Insolvency: 132
  },
  {
    Economy: "Paraguay",
    Global_Rank: 113,
    Starting_a_Business: 151,
    Dealing_with_Construction_Permits: 79,
    Getting_Electricity: 101,
    Registering_Property: 74,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 127,
    Trading_across_Borders: 127,
    Enforcing_Contracts: 91,
    Resolving_Insolvency: 103
  },
  {
    Economy: "Ghana",
    Global_Rank: 114,
    Starting_a_Business: 108,
    Dealing_with_Construction_Permits: 115,
    Getting_Electricity: 86,
    Registering_Property: 123,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 115,
    Trading_across_Borders: 156,
    Enforcing_Contracts: 116,
    Resolving_Insolvency: 160
  },
  {
    Economy: "Solomon Islands",
    Global_Rank: 115,
    Starting_a_Business: 98,
    Dealing_with_Construction_Permits: 53,
    Getting_Electricity: 92,
    Registering_Property: 154,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 38,
    Trading_across_Borders: 160,
    Enforcing_Contracts: 156,
    Resolving_Insolvency: 144
  },
  {
    Economy: "West Bank and Gaza",
    Global_Rank: 116,
    Starting_a_Business: 171,
    Dealing_with_Construction_Permits: 157,
    Getting_Electricity: 85,
    Registering_Property: 84,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 161,
    Paying_Taxes: 107,
    Trading_across_Borders: 54,
    Enforcing_Contracts: 123,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Eswatini",
    Global_Rank: 117,
    Starting_a_Business: 159,
    Dealing_with_Construction_Permits: 107,
    Getting_Electricity: 163,
    Registering_Property: 107,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 63,
    Trading_across_Borders: 32,
    Enforcing_Contracts: 172,
    Resolving_Insolvency: 119
  },
  {
    Economy: "Bahamas, The",
    Global_Rank: 118,
    Starting_a_Business: 105,
    Dealing_with_Construction_Permits: 91,
    Getting_Electricity: 87,
    Registering_Property: 169,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 50,
    Trading_across_Borders: 161,
    Enforcing_Contracts: 84,
    Resolving_Insolvency: 69
  },
  {
    Economy: "Argentina",
    Global_Rank: 119,
    Starting_a_Business: 128,
    Dealing_with_Construction_Permits: 174,
    Getting_Electricity: 103,
    Registering_Property: 119,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 57,
    Paying_Taxes: 169,
    Trading_across_Borders: 125,
    Enforcing_Contracts: 107,
    Resolving_Insolvency: 104
  },
  {
    Economy: "Egypt, Arab Rep.",
    Global_Rank: 120,
    Starting_a_Business: 109,
    Dealing_with_Construction_Permits: 68,
    Getting_Electricity: 96,
    Registering_Property: 125,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 72,
    Paying_Taxes: 159,
    Trading_across_Borders: 171,
    Enforcing_Contracts: 160,
    Resolving_Insolvency: 101
  },
  {
    Economy: "Honduras",
    Global_Rank: 121,
    Starting_a_Business: 154,
    Dealing_with_Construction_Permits: 116,
    Getting_Electricity: 153,
    Registering_Property: 95,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 164,
    Trading_across_Borders: 123,
    Enforcing_Contracts: 152,
    Resolving_Insolvency: 143
  },
  {
    Economy: "Ivory Coast",
    Global_Rank: 122,
    Starting_a_Business: 26,
    Dealing_with_Construction_Permits: 142,
    Getting_Electricity: 143,
    Registering_Property: 112,
    Getting_Credit: 44,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 175,
    Trading_across_Borders: 162,
    Enforcing_Contracts: 106,
    Resolving_Insolvency: 80
  },
  {
    Economy: "Ecuador",
    Global_Rank: 123,
    Starting_a_Business: 168,
    Dealing_with_Construction_Permits: 113,
    Getting_Electricity: 94,
    Registering_Property: 75,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 143,
    Trading_across_Borders: 109,
    Enforcing_Contracts: 79,
    Resolving_Insolvency: 158
  },
  {
    Economy: "Philippines",
    Global_Rank: 124,
    Starting_a_Business: 166,
    Dealing_with_Construction_Permits: 94,
    Getting_Electricity: 29,
    Registering_Property: 116,
    Getting_Credit: 184,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 94,
    Trading_across_Borders: 104,
    Enforcing_Contracts: 151,
    Resolving_Insolvency: 63
  },
  {
    Economy: "Belize",
    Global_Rank: 125,
    Starting_a_Business: 162,
    Dealing_with_Construction_Permits: 119,
    Getting_Electricity: 91,
    Registering_Property: 135,
    Getting_Credit: 172,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 52,
    Trading_across_Borders: 111,
    Enforcing_Contracts: 133,
    Resolving_Insolvency: 87
  },
  {
    Economy: "Tajikistan",
    Global_Rank: 126,
    Starting_a_Business: 60,
    Dealing_with_Construction_Permits: 135,
    Getting_Electricity: 173,
    Registering_Property: 91,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 136,
    Trading_across_Borders: 148,
    Enforcing_Contracts: 61,
    Resolving_Insolvency: 146
  },
  {
    Economy: "Uganda",
    Global_Rank: 127,
    Starting_a_Business: 164,
    Dealing_with_Construction_Permits: 145,
    Getting_Electricity: 175,
    Registering_Property: 126,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 87,
    Trading_across_Borders: 119,
    Enforcing_Contracts: 71,
    Resolving_Insolvency: 112
  },
  {
    Economy: "Iran, Islamic Rep.",
    Global_Rank: 128,
    Starting_a_Business: 173,
    Dealing_with_Construction_Permits: 86,
    Getting_Electricity: 108,
    Registering_Property: 90,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 173,
    Paying_Taxes: 149,
    Trading_across_Borders: 121,
    Enforcing_Contracts: 89,
    Resolving_Insolvency: 131
  },
  {
    Economy: "Barbados",
    Global_Rank: 129,
    Starting_a_Business: 101,
    Dealing_with_Construction_Permits: 154,
    Getting_Electricity: 114,
    Registering_Property: 129,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 168,
    Paying_Taxes: 93,
    Trading_across_Borders: 132,
    Enforcing_Contracts: 170,
    Resolving_Insolvency: 34
  },
  {
    Economy: "St. Vincent and the Grenadines",
    Global_Rank: 130,
    Starting_a_Business: 88,
    Dealing_with_Construction_Permits: 49,
    Getting_Electricity: 98,
    Registering_Property: 171,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 103,
    Trading_across_Borders: 81,
    Enforcing_Contracts: 56,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Cabo Verde",
    Global_Rank: 131,
    Starting_a_Business: 116,
    Dealing_with_Construction_Permits: 43,
    Getting_Electricity: 155,
    Registering_Property: 70,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 165,
    Paying_Taxes: 77,
    Trading_across_Borders: 114,
    Enforcing_Contracts: 45,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Nicaragua",
    Global_Rank: 132,
    Starting_a_Business: 144,
    Dealing_with_Construction_Permits: 177,
    Getting_Electricity: 110,
    Registering_Property: 155,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 168,
    Paying_Taxes: 160,
    Trading_across_Borders: 85,
    Enforcing_Contracts: 87,
    Resolving_Insolvency: 106
  },
  {
    Economy: "Palau",
    Global_Rank: 133,
    Starting_a_Business: 129,
    Dealing_with_Construction_Permits: 95,
    Getting_Electricity: 149,
    Registering_Property: 43,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 180,
    Paying_Taxes: 106,
    Trading_across_Borders: 137,
    Enforcing_Contracts: 126,
    Resolving_Insolvency: 166
  },
  {
    Economy: "Guyana",
    Global_Rank: 134,
    Starting_a_Business: 97,
    Dealing_with_Construction_Permits: 164,
    Getting_Electricity: 165,
    Registering_Property: 117,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 119,
    Trading_across_Borders: 146,
    Enforcing_Contracts: 93,
    Resolving_Insolvency: 162
  },
  {
    Economy: "Mozambique",
    Global_Rank: 135,
    Starting_a_Business: 174,
    Dealing_with_Construction_Permits: 64,
    Getting_Electricity: 100,
    Registering_Property: 133,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 125,
    Trading_across_Borders: 91,
    Enforcing_Contracts: 167,
    Resolving_Insolvency: 84
  },
  {
    Economy: "Pakistan",
    Global_Rank: 136,
    Starting_a_Business: 130,
    Dealing_with_Construction_Permits: 166,
    Getting_Electricity: 167,
    Registering_Property: 161,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 26,
    Paying_Taxes: 173,
    Trading_across_Borders: 142,
    Enforcing_Contracts: 156,
    Resolving_Insolvency: 53
  },
  {
    Economy: "Togo",
    Global_Rank: 137,
    Starting_a_Business: 74,
    Dealing_with_Construction_Permits: 133,
    Getting_Electricity: 105,
    Registering_Property: 127,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 172,
    Trading_across_Borders: 129,
    Enforcing_Contracts: 137,
    Resolving_Insolvency: 86
  },
  {
    Economy: "Cambodia",
    Global_Rank: 138,
    Starting_a_Business: 185,
    Dealing_with_Construction_Permits: 179,
    Getting_Electricity: 141,
    Registering_Property: 124,
    Getting_Credit: 22,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 137,
    Trading_across_Borders: 115,
    Enforcing_Contracts: 182,
    Resolving_Insolvency: 79
  },
  {
    Economy: "Maldives",
    Global_Rank: 139,
    Starting_a_Business: 71,
    Dealing_with_Construction_Permits: 62,
    Getting_Electricity: 145,
    Registering_Property: 175,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 117,
    Trading_across_Borders: 155,
    Enforcing_Contracts: 125,
    Resolving_Insolvency: 139
  },
  {
    Economy: "St. Kitts and Nevis",
    Global_Rank: 140,
    Starting_a_Business: 95,
    Dealing_with_Construction_Permits: 47,
    Getting_Electricity: 102,
    Registering_Property: 185,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 122,
    Paying_Taxes: 124,
    Trading_across_Borders: 68,
    Enforcing_Contracts: 51,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Senegal",
    Global_Rank: 141,
    Starting_a_Business: 64,
    Dealing_with_Construction_Permits: 140,
    Getting_Electricity: 127,
    Registering_Property: 118,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 171,
    Trading_across_Borders: 139,
    Enforcing_Contracts: 142,
    Resolving_Insolvency: 94
  },
  {
    Economy: "Lebanon",
    Global_Rank: 142,
    Starting_a_Business: 146,
    Dealing_with_Construction_Permits: 170,
    Getting_Electricity: 124,
    Registering_Property: 105,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 113,
    Trading_across_Borders: 150,
    Enforcing_Contracts: 135,
    Resolving_Insolvency: 151
  },
  {
    Economy: "Niger",
    Global_Rank: 143,
    Starting_a_Business: 27,
    Dealing_with_Construction_Permits: 158,
    Getting_Electricity: 162,
    Registering_Property: 111,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 161,
    Trading_across_Borders: 124,
    Enforcing_Contracts: 119,
    Resolving_Insolvency: 114
  },
  {
    Economy: "Tanzania",
    Global_Rank: 144,
    Starting_a_Business: 163,
    Dealing_with_Construction_Permits: 150,
    Getting_Electricity: 83,
    Registering_Property: 146,
    Getting_Credit: 60,
    Protecting_Minority_Investors: 131,
    Paying_Taxes: 167,
    Trading_across_Borders: 183,
    Enforcing_Contracts: 64,
    Resolving_Insolvency: 117
  },
  {
    Economy: "Mali",
    Global_Rank: 145,
    Starting_a_Business: 110,
    Dealing_with_Construction_Permits: 109,
    Getting_Electricity: 159,
    Registering_Property: 141,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 165,
    Trading_across_Borders: 92,
    Enforcing_Contracts: 159,
    Resolving_Insolvency: 97
  },
  {
    Economy: "Nigeria",
    Global_Rank: 146,
    Starting_a_Business: 120,
    Dealing_with_Construction_Permits: 149,
    Getting_Electricity: 171,
    Registering_Property: 184,
    Getting_Credit: 12,
    Protecting_Minority_Investors: 38,
    Paying_Taxes: 157,
    Trading_across_Borders: 182,
    Enforcing_Contracts: 92,
    Resolving_Insolvency: 149
  },
  {
    Economy: "Grenada",
    Global_Rank: 147,
    Starting_a_Business: 85,
    Dealing_with_Construction_Permits: 130,
    Getting_Electricity: 89,
    Registering_Property: 146,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 142,
    Trading_across_Borders: 135,
    Enforcing_Contracts: 80,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Mauritania",
    Global_Rank: 148,
    Starting_a_Business: 46,
    Dealing_with_Construction_Permits: 92,
    Getting_Electricity: 151,
    Registering_Property: 102,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 110,
    Paying_Taxes: 178,
    Trading_across_Borders: 141,
    Enforcing_Contracts: 72,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Gambia, The",
    Global_Rank: 149,
    Starting_a_Business: 169,
    Dealing_with_Construction_Permits: 123,
    Getting_Electricity: 160,
    Registering_Property: 132,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 165,
    Paying_Taxes: 169,
    Trading_across_Borders: 113,
    Enforcing_Contracts: 117,
    Resolving_Insolvency: 128
  },
  {
    Economy: "Marshall Islands",
    Global_Rank: 150,
    Starting_a_Business: 75,
    Dealing_with_Construction_Permits: 73,
    Getting_Electricity: 132,
    Registering_Property: 187,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 180,
    Paying_Taxes: 70,
    Trading_across_Borders: 75,
    Enforcing_Contracts: 103,
    Resolving_Insolvency: 167
  },
  {
    Economy: "Burkina Faso",
    Global_Rank: 151,
    Starting_a_Business: 79,
    Dealing_with_Construction_Permits: 58,
    Getting_Electricity: 181,
    Registering_Property: 145,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 153,
    Trading_across_Borders: 120,
    Enforcing_Contracts: 165,
    Resolving_Insolvency: 107
  },
  {
    Economy: "Guinea",
    Global_Rank: 152,
    Starting_a_Business: 111,
    Dealing_with_Construction_Permits: 50,
    Getting_Electricity: 146,
    Registering_Property: 138,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 181,
    Trading_across_Borders: 167,
    Enforcing_Contracts: 118,
    Resolving_Insolvency: 116
  },
  {
    Economy: "Benin",
    Global_Rank: 153,
    Starting_a_Business: 61,
    Dealing_with_Construction_Permits: 51,
    Getting_Electricity: 176,
    Registering_Property: 130,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 176,
    Trading_across_Borders: 107,
    Enforcing_Contracts: 171,
    Resolving_Insolvency: 110
  },
  {
    Economy: "Lao PDR",
    Global_Rank: 154,
    Starting_a_Business: 180,
    Dealing_with_Construction_Permits: 99,
    Getting_Electricity: 156,
    Registering_Property: 85,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 174,
    Paying_Taxes: 155,
    Trading_across_Borders: 76,
    Enforcing_Contracts: 162,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Zimbabwe",
    Global_Rank: 155,
    Starting_a_Business: 176,
    Dealing_with_Construction_Permits: 176,
    Getting_Electricity: 166,
    Registering_Property: 109,
    Getting_Credit: 85,
    Protecting_Minority_Investors: 95,
    Paying_Taxes: 145,
    Trading_across_Borders: 157,
    Enforcing_Contracts: 168,
    Resolving_Insolvency: 159
  },
  {
    Economy: "Bolivia",
    Global_Rank: 156,
    Starting_a_Business: 178,
    Dealing_with_Construction_Permits: 160,
    Getting_Electricity: 111,
    Registering_Property: 148,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 186,
    Trading_across_Borders: 96,
    Enforcing_Contracts: 113,
    Resolving_Insolvency: 102
  },
  {
    Economy: "Algeria",
    Global_Rank: 157,
    Starting_a_Business: 150,
    Dealing_with_Construction_Permits: 129,
    Getting_Electricity: 106,
    Registering_Property: 165,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 168,
    Paying_Taxes: 156,
    Trading_across_Borders: 173,
    Enforcing_Contracts: 112,
    Resolving_Insolvency: 76
  },
  {
    Economy: "Kiribati",
    Global_Rank: 158,
    Starting_a_Business: 149,
    Dealing_with_Construction_Permits: 117,
    Getting_Electricity: 170,
    Registering_Property: 149,
    Getting_Credit: 172,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 96,
    Trading_across_Borders: 131,
    Enforcing_Contracts: 120,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Ethiopia",
    Global_Rank: 159,
    Starting_a_Business: 167,
    Dealing_with_Construction_Permits: 168,
    Getting_Electricity: 131,
    Registering_Property: 144,
    Getting_Credit: 175,
    Protecting_Minority_Investors: 178,
    Paying_Taxes: 130,
    Trading_across_Borders: 154,
    Enforcing_Contracts: 60,
    Resolving_Insolvency: 148
  },
  {
    Economy: "Micronesia, Fed. Sts.",
    Global_Rank: 160,
    Starting_a_Business: 170,
    Dealing_with_Construction_Permits: 137,
    Getting_Electricity: 117,
    Registering_Property: 187,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 185,
    Paying_Taxes: 110,
    Trading_across_Borders: 61,
    Enforcing_Contracts: 184,
    Resolving_Insolvency: 123
  },
  {
    Economy: "Madagascar",
    Global_Rank: 161,
    Starting_a_Business: 81,
    Dealing_with_Construction_Permits: 183,
    Getting_Electricity: 185,
    Registering_Property: 162,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 132,
    Trading_across_Borders: 138,
    Enforcing_Contracts: 150,
    Resolving_Insolvency: 136
  },
  {
    Economy: "Sudan",
    Global_Rank: 162,
    Starting_a_Business: 156,
    Dealing_with_Construction_Permits: 105,
    Getting_Electricity: 120,
    Registering_Property: 93,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 168,
    Paying_Taxes: 163,
    Trading_across_Borders: 185,
    Enforcing_Contracts: 144,
    Resolving_Insolvency: 118
  },
  {
    Economy: "Sierra Leone",
    Global_Rank: 163,
    Starting_a_Business: 55,
    Dealing_with_Construction_Permits: 182,
    Getting_Electricity: 178,
    Registering_Property: 167,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 88,
    Trading_across_Borders: 166,
    Enforcing_Contracts: 105,
    Resolving_Insolvency: 161
  },
  {
    Economy: "Comoros",
    Global_Rank: 164,
    Starting_a_Business: 164,
    Dealing_with_Construction_Permits: 85,
    Getting_Electricity: 139,
    Registering_Property: 114,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 168,
    Trading_across_Borders: 118,
    Enforcing_Contracts: 179,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Suriname",
    Global_Rank: 165,
    Starting_a_Business: 182,
    Dealing_with_Construction_Permits: 114,
    Getting_Electricity: 138,
    Registering_Property: 160,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 168,
    Paying_Taxes: 105,
    Trading_across_Borders: 87,
    Enforcing_Contracts: 187,
    Resolving_Insolvency: 138
  },
  {
    Economy: "Cameroon",
    Global_Rank: 166,
    Starting_a_Business: 92,
    Dealing_with_Construction_Permits: 132,
    Getting_Electricity: 129,
    Registering_Property: 176,
    Getting_Credit: 73,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 182,
    Trading_across_Borders: 186,
    Enforcing_Contracts: 166,
    Resolving_Insolvency: 127
  },
  {
    Economy: "Afghanistan",
    Global_Rank: 167,
    Starting_a_Business: 49,
    Dealing_with_Construction_Permits: 184,
    Getting_Electricity: 168,
    Registering_Property: 186,
    Getting_Credit: 99,
    Protecting_Minority_Investors: 26,
    Paying_Taxes: 177,
    Trading_across_Borders: 177,
    Enforcing_Contracts: 181,
    Resolving_Insolvency: 74
  },
  {
    Economy: "Burundi",
    Global_Rank: 168,
    Starting_a_Business: 17,
    Dealing_with_Construction_Permits: 162,
    Getting_Electricity: 183,
    Registering_Property: 97,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 138,
    Trading_across_Borders: 169,
    Enforcing_Contracts: 158,
    Resolving_Insolvency: 147
  },
  {
    Economy: "Gabon",
    Global_Rank: 169,
    Starting_a_Business: 124,
    Dealing_with_Construction_Permits: 144,
    Getting_Electricity: 161,
    Registering_Property: 178,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 161,
    Paying_Taxes: 183,
    Trading_across_Borders: 170,
    Enforcing_Contracts: 180,
    Resolving_Insolvency: 129
  },
  {
    Economy: "Sao Tome and Principe",
    Global_Rank: 170,
    Starting_a_Business: 148,
    Dealing_with_Construction_Permits: 111,
    Getting_Electricity: 125,
    Registering_Property: 173,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 188,
    Paying_Taxes: 135,
    Trading_across_Borders: 122,
    Enforcing_Contracts: 185,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Iraq",
    Global_Rank: 171,
    Starting_a_Business: 155,
    Dealing_with_Construction_Permits: 103,
    Getting_Electricity: 126,
    Registering_Property: 113,
    Getting_Credit: 186,
    Protecting_Minority_Investors: 125,
    Paying_Taxes: 129,
    Trading_across_Borders: 181,
    Enforcing_Contracts: 143,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Myanmar",
    Global_Rank: 171,
    Starting_a_Business: 152,
    Dealing_with_Construction_Permits: 81,
    Getting_Electricity: 144,
    Registering_Property: 136,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 185,
    Paying_Taxes: 126,
    Trading_across_Borders: 168,
    Enforcing_Contracts: 188,
    Resolving_Insolvency: 164
  },
  {
    Economy: "Angola",
    Global_Rank: 173,
    Starting_a_Business: 139,
    Dealing_with_Construction_Permits: 87,
    Getting_Electricity: 152,
    Registering_Property: 170,
    Getting_Credit: 184,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 104,
    Trading_across_Borders: 174,
    Enforcing_Contracts: 186,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Liberia",
    Global_Rank: 174,
    Starting_a_Business: 80,
    Dealing_with_Construction_Permits: 185,
    Getting_Electricity: 172,
    Registering_Property: 182,
    Getting_Credit: 112,
    Protecting_Minority_Investors: 180,
    Paying_Taxes: 67,
    Trading_across_Borders: 179,
    Enforcing_Contracts: 175,
    Resolving_Insolvency: 111
  },
  {
    Economy: "Guinea-Bissau",
    Global_Rank: 175,
    Starting_a_Business: 158,
    Dealing_with_Construction_Permits: 178,
    Getting_Electricity: 180,
    Registering_Property: 128,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 140,
    Paying_Taxes: 154,
    Trading_across_Borders: 144,
    Enforcing_Contracts: 169,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Bangladesh",
    Global_Rank: 176,
    Starting_a_Business: 138,
    Dealing_with_Construction_Permits: 138,
    Getting_Electricity: 179,
    Registering_Property: 183,
    Getting_Credit: 161,
    Protecting_Minority_Investors: 89,
    Paying_Taxes: 151,
    Trading_across_Borders: 176,
    Enforcing_Contracts: 189,
    Resolving_Insolvency: 153
  },
  {
    Economy: "Equatorial Guinea",
    Global_Rank: 177,
    Starting_a_Business: 184,
    Dealing_with_Construction_Permits: 163,
    Getting_Electricity: 150,
    Registering_Property: 164,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 179,
    Trading_across_Borders: 175,
    Enforcing_Contracts: 101,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Timor-Leste",
    Global_Rank: 178,
    Starting_a_Business: 68,
    Dealing_with_Construction_Permits: 161,
    Getting_Electricity: 123,
    Registering_Property: 187,
    Getting_Credit: 172,
    Protecting_Minority_Investors: 99,
    Paying_Taxes: 140,
    Trading_across_Borders: 104,
    Enforcing_Contracts: 190,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Syrian Arab Republic",
    Global_Rank: 179,
    Starting_a_Business: 136,
    Dealing_with_Construction_Permits: 186,
    Getting_Electricity: 158,
    Registering_Property: 157,
    Getting_Credit: 175,
    Protecting_Minority_Investors: 95,
    Paying_Taxes: 85,
    Trading_across_Borders: 178,
    Enforcing_Contracts: 161,
    Resolving_Insolvency: 163
  },
  {
    Economy: "Congo, Rep.",
    Global_Rank: 180,
    Starting_a_Business: 179,
    Dealing_with_Construction_Permits: 127,
    Getting_Electricity: 182,
    Registering_Property: 177,
    Getting_Credit: 134,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 185,
    Trading_across_Borders: 184,
    Enforcing_Contracts: 155,
    Resolving_Insolvency: 122
  },
  {
    Economy: "Chad",
    Global_Rank: 181,
    Starting_a_Business: 186,
    Dealing_with_Construction_Permits: 153,
    Getting_Electricity: 177,
    Registering_Property: 134,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 161,
    Paying_Taxes: 188,
    Trading_across_Borders: 172,
    Enforcing_Contracts: 153,
    Resolving_Insolvency: 154
  },
  {
    Economy: "Haiti",
    Global_Rank: 182,
    Starting_a_Business: 189,
    Dealing_with_Construction_Permits: 180,
    Getting_Electricity: 142,
    Registering_Property: 181,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 188,
    Paying_Taxes: 147,
    Trading_across_Borders: 86,
    Enforcing_Contracts: 124,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Central African Republic",
    Global_Rank: 183,
    Starting_a_Business: 181,
    Dealing_with_Construction_Permits: 181,
    Getting_Electricity: 184,
    Registering_Property: 172,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 149,
    Paying_Taxes: 187,
    Trading_across_Borders: 163,
    Enforcing_Contracts: 183,
    Resolving_Insolvency: 154
  },
  {
    Economy: "Congo, Dem. Rep.",
    Global_Rank: 184,
    Starting_a_Business: 62,
    Dealing_with_Construction_Permits: 165,
    Getting_Electricity: 174,
    Registering_Property: 156,
    Getting_Credit: 144,
    Protecting_Minority_Investors: 165,
    Paying_Taxes: 180,
    Trading_across_Borders: 188,
    Enforcing_Contracts: 178,
    Resolving_Insolvency: 168
  },
  {
    Economy: "South Sudan",
    Global_Rank: 185,
    Starting_a_Business: 177,
    Dealing_with_Construction_Permits: 169,
    Getting_Electricity: 187,
    Registering_Property: 179,
    Getting_Credit: 178,
    Protecting_Minority_Investors: 180,
    Paying_Taxes: 66,
    Trading_across_Borders: 180,
    Enforcing_Contracts: 85,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Libya",
    Global_Rank: 186,
    Starting_a_Business: 160,
    Dealing_with_Construction_Permits: 186,
    Getting_Electricity: 136,
    Registering_Property: 187,
    Getting_Credit: 186,
    Protecting_Minority_Investors: 185,
    Paying_Taxes: 128,
    Trading_across_Borders: 128,
    Enforcing_Contracts: 141,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Yemen, Rep.",
    Global_Rank: 187,
    Starting_a_Business: 175,
    Dealing_with_Construction_Permits: 186,
    Getting_Electricity: 187,
    Registering_Property: 81,
    Getting_Credit: 186,
    Protecting_Minority_Investors: 132,
    Paying_Taxes: 83,
    Trading_across_Borders: 189,
    Enforcing_Contracts: 139,
    Resolving_Insolvency: 157
  },
  {
    Economy: "Venezuela, RB",
    Global_Rank: 188,
    Starting_a_Business: 190,
    Dealing_with_Construction_Permits: 152,
    Getting_Electricity: 186,
    Registering_Property: 138,
    Getting_Credit: 124,
    Protecting_Minority_Investors: 180,
    Paying_Taxes: 189,
    Trading_across_Borders: 187,
    Enforcing_Contracts: 148,
    Resolving_Insolvency: 165
  },
  {
    Economy: "Eritrea",
    Global_Rank: 189,
    Starting_a_Business: 187,
    Dealing_with_Construction_Permits: 186,
    Getting_Electricity: 187,
    Registering_Property: 180,
    Getting_Credit: 186,
    Protecting_Minority_Investors: 174,
    Paying_Taxes: 152,
    Trading_across_Borders: 189,
    Enforcing_Contracts: 103,
    Resolving_Insolvency: 168
  },
  {
    Economy: "Somalia",
    Global_Rank: 190,
    Starting_a_Business: 188,
    Dealing_with_Construction_Permits: 186,
    Getting_Electricity: 187,
    Registering_Property: 152,
    Getting_Credit: 186,
    Protecting_Minority_Investors: 190,
    Paying_Taxes: 190,
    Trading_across_Borders: 164,
    Enforcing_Contracts: 114,
    Resolving_Insolvency: 168
  }
];
export const starterEconomy = {
  Economy: "New Zealand",
  Global_Rank: 1,
  Starting_a_Business: 1,
  Dealing_with_Construction_Permits: 6,
  Getting_Electricity: 45,
  Registering_Property: 1,
  Getting_Credit: 1,
  Protecting_Minority_Investors: 2,
  Paying_Taxes: 10,
  Trading_across_Borders: 60,
  Enforcing_Contracts: 21,
  Resolving_Insolvency: 31
};
